theme: jekyll-theme-midnight
show_downloads: true
author: Hossein Shahpouri
navbar-links:
  Author's home: "https://hshahpouri.net"
social-network-links:
  email: hshahpouri@outlook.com
  linkedin: hshahpouri
  github: hshahpouri
  telegram: hshahpouri
share-links-active:
  telegram: true
  github: true
  linkedin: true
